### ISSUE TITLE
python-parquet with Python 3 

### ISSUE THREAD

**Issue by mpage38** [jcrobak/parquet-python#15]
python-parquet relies on cStringIO, which is gone in python 3. Is there a plan for porting python-parquet to python 3 ?

**Comment by jcrobak** [comment]
I started a branch to add support a few months ago. At the time, thrift didn't support Python 3. There's a non Apache thrift impl, but it didn't support the TCompact protocol. I'll try to reevaluate soon

**Comment by hshteingart** [comment]
used 2to3 and install thrift using pip install. The interface is missing DictReader and the other loading functions.

**Comment by martindurant** [comment]
My partial rewrite in https://github.com/jcrobak/parquet-python/pull/13 was designed for python3 and has also other improvements such as vectorised numpy/pandas reading and a partial writing interface.

**Comment by turicas** [comment]
Is thrift really needed? I mean: the work to convert it to pure-python is too large?

**Comment by jcrobak** [comment]
@turicas master now has python3 support. I can push a new release, but it'd be great to have someone verify that it's working for them first.

**Comment by turicas** [comment]
@jcrobak I made some tests here and it's working both on Python 2 and 3! :) I'm still working on Python 3 support for my library rows (on [feature/python3-support](https://github.com/turicas/rows/tree/feature/python3-support)) but parquet is not an issue anymore. :)
If you could, please release on PyPI. :smile:

**Comment by jcrobak** [comment]
@turicas version 1.1 was just released and pushed to pypi!

**Comment by turicas** [comment]
@jcrobak, thanks! Already included this version (`parquet>=1.1`) on rows' `setup.py`. =)
