### ISSUE TITLE
Reading gzip compressed parquet files

### ISSUE THREAD

**Issue by marcelopham** [jcrobak/parquet-python#19]
Hello!
How can I read a compressed parquet file ("filename.gz.parquet")?
I tried reading it straight and it's giving me an assertion error:

with open('part-0001.gz.parquet') as fo:
  for r in parquet.DictReader(fo): print r
Traceback (most recent call last):
  File <stdin>, line 2, in <module>
  File "build/bdist.macosx-10.11-x86_64/egg/parquet/__init__.py", line 356, in DictReader
  File "build/bdist.macosx-10.11-x86_64/egg/parquet/__init__.py", line 371, in reader
  File "build/bdist.macosx-10.11-x86_64/egg/parquet/schema.py", line 12, in __init__
AssertionError

Thanks!

M

**Comment by sylvinus** [comment]
Would love to be able to do that as well!

**Comment by jcrobak** [comment]
In my simple testing, I'm able to read gzip compressed files. Do you have an example file, or a way to produce a file that fails? Thanks

**Comment by marcelopham** [comment]
Thanks Joe - sorry for the late reply.
I have tried a gz.parquet compressed file and worked fine with your lib - turns out the files I was trying to read has a modified header (probably forced) so the assertion error was caused by the mismatch ... working on a workaround.

Thanks again!
M

**Comment by natank1** [comment]
I have used the parquet folder for gz.parquet. Both in parquet.reader & parquet.DictReader , when I did not give explicit columns it collpaes wit an error message fromread_data_page in the definition_levels if.
