### ISSUE TITLE
TypeError: Struct() argument 1 must be string, not unicode

### ISSUE THREAD

**Issue by datazhen** [jcrobak/parquet-python#31]
I'm testing this script and rising the error:TypeError: Struct() argument 1 must be string, not unicode
```
with open("nation.dict.parquet") as fo:
    for row in parquet.DictReader(fo):
        print str(row)
```

**Comment by jcrobak** [comment]
@datazhen could you try opening the file in binary mode to see if that resolves it?

**Comment by jcrobak** [comment]
@datazhen I cannot reproduce this. Could you provide a few more details? python version, full stack trace, etc?

**Comment by jcrobak** [comment]
I think some recent changes have fixed this issue. please reopen if not.
