### ISSUE TITLE
bit_width of 0 causes a crash

### ISSUE THREAD

**Issue by makrisoft** [jcrobak/parquet-python#47]
in read_data_page() of parquet/__init__.py
when the bit_width is zero, we need to implement what this class provides:
https://github.com/apache/parquet-mr/blob/e54ca615f213f5db6d34d9163c97eec98920d7a7/parquet-column/src/main/java/org/apache/parquet/column/values/rle/ZeroIntegerValuesReader.java

I have a fix for this, but I need to test this some more:
```
        if bit_width == 0:
            vals += [dictionary[0] for i in range(0,daph.num_values)]
        else:
            # TODO jcrobak -- not sure that this loop is needed?
            while total_seen < daph.num_values:
                values = encoding.read_rle_bit_packed_hybrid(
                    dict_values_io_obj, bit_width, len(dict_values_bytes))
                if len(values) + total_seen > daph.num_values:
                    values = values[0: daph.num_values - total_seen]
                vals += [dictionary[v] for v in values]
                total_seen += len(values)
```

the problem happens on a very small parquet file with, in my case, just 4 rows.
The problem row represents a user_id and all row user_ids are the same. The user id bytes are stored in the dictionary section, and from what I could gather from the java code, one is supposed to replicate the one dictionary value by `daph.num_values` times.

**Comment by jcrobak** [comment]
Should be resolved by #60
