### ISSUE TITLE
Mandatory snappy installation

### ISSUE THREAD

**Issue by ran-z** [jcrobak/parquet-python#64]
Some use cases don't involve Snappy usage, and indeed it seems the code can handle scenarios where `python-snappy` is not installed; However, the `parquet-python` package does require `python-snappy` explicitly (thereby also possibly forcing installation of system dependencies required by `python-snappy` such as `snappy` itself).

Is it ok if I made a PR to have `python-snappy` an optional requirement in `setup.py` (i.e. it would not get installed by default but rather only when pip is used like so: `pip install parquet-python[snappy]`)?

**Comment by jcrobak** [comment]
good catch, pr would be great!
