### ISSUE TITLE
Upload to PyPI

### ISSUE THREAD

**Issue by turicas** [jcrobak/parquet-python#9]
I'm creating the [Parquet rows plugin](https://github.com/turicas/rows/issues/150) and need this library available on PyPI to do it properly.

As it was not available there and the last commit here is almost 1 year old, I've uploaded it: https://pypi.python.org/pypi/parquet

@jcrobak, if you want access on PyPI, please tell me your username and I can give you.

If the library is not maintained anymore, then probably I'm going to create a fork of it and maintain the version on PyPI with the fork.

**Comment by jcrobak** [comment]
Cool! I don't have much time to work on it right now, so I can't promise anything...but would be willing to try to help.

**Comment by peterbe** [comment]
@turicas Did you ever make any progress with a fork?

**Comment by turicas** [comment]
@peterbe, no, I didn't fork since it worked as expected for me and I don't have too much demand on using Parket files. Do you have any additional needs?

**Comment by peterbe** [comment]
> Do you have any additional needs?

Being able to write/create parquet files.

**Comment by turicas** [comment]
Sorry, I don't have enough time to dig into this kind of development now, since I'm not needing this feature in my current projects.

**Comment by jcrobak** [comment]
@turicas could you add me on pypi? I'm jcrobak. Thanks!

**Comment by turicas** [comment]
@jcrobak, already added! Please go to https://pypi.python.org/pypi/parquet and see the package administration page. :)

Since the package is already on PyPI and you now have access to it, I'm closing this issue.
